### PR TITLE
Handle multiple keywords and parse windows carriage return.

### PR DESCRIPTION
**Pull request by JAForbes**
Fixes achesco/extract-iptc#1 and achesco/extract-iptc#2

### CODE REVIEW

**Comment by achesco** [comment]
Please, check updated master. Used your 'extra quotation mark and carriage return' fix but don't realy like an idea of per-tag 'onvalue' processor.

**Comment by JAForbes** [comment]
@achesco 

> but don't realy like an idea of per-tag 'onvalue' processor.

:+1: 

Any chance of getting this published to npm?

**Comment by achesco** [comment]
> Any chance of getting this published to npm?

Sure, done

**Comment by JAForbes** [comment]
Thank you

-----Original Message-----

**Pull request closed without merging**
